#!/bin/bash

STAGED_FILES=$(git diff --cached --name-only --diff-filter ACMR | grep ".tsx\{0,1\}$")

if [[ "$STAGED_FILES" = "" ]]; then
  exit 0
fi

# Check for eslint
ESLINT="./node_modules/.bin/eslint"
if [[ ! -e $ESLINT ]]; then
  echo ""
  echo "  Please use <npm install> to install ESlint"
  exit 1
fi;

PASS=true
echo ""

for FILE in $STAGED_FILES
do
  $ESLINT "$FILE"

  if [[ "$?" == 0 ]]; then
    echo "  ESLint Passed: $FILE"
  else
    echo "  ESLint Failed: $FILE"
    PASS=false
  fi
done

echo ""
if ! $PASS; then
  echo "  COMMIT FAILED: Your commit contains files that should pass ESLint but do not. Please fix the ESLint errors and try again. "
  exit 1
else
  echo "  COMMIT SUCCEEDED "
fi

exit $?